
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS memos;
CREATE TABLE memos (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, title VARCHAR (32), text VARCHAR (275), color VARCHAR (275), create_date DATE);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
